### ISSUE TITLE
Heap out of memory error: Memory hungry

### ISSUE THREAD

**Issue by TheAifam5** [astrelsky/Ghidra-Cpp-Class-Analyzer#13] opened 2020-04-07 23:37 UTC
On 64GB RAM with 38GB SWAP machine, analyzing big binaries (about 10-20mb) takes even more than 6 hours (once even 14h on i9-9900k) and most of the binaries just crashing in the middle with an error as the title. I tried to analyze one by one but the same issue occurs. Do you maybe know why the CppClassAnalyzer is so memory hungry?

Regards,
TheAifam5

**Comment by astrelsky** [comment] 2020-04-08 03:33
> On 64GB RAM with 38GB SWAP machine, analyzing big binaries (about 10-20mb) takes even more than 6 hours (once even 14h on i9-9900k) and most of the binaries just crashing in the middle with an error as the title. I tried to analyze one by one but the same issue occurs. Do you maybe know why the CppClassAnalyzer is so memory hungry?
> 
> Regards,
> TheAifam5

Unfortunately the only solution to how much memory it consumes would be to create db entries in ghidra's internal db. This would be in the same fashion as the GhidraClassDB, SymbolDB, etc etc. I started on it a few months ago but didn't get very far before the spring semester started. This was sort of something I had hoped would come along as a result of getting the GccRttiAnalyzer merged into ghidra but I don't think it will happen anytime soon. 

At the moment the analyzers currently search out all type_info instances and their vtables and stores them.

The most I've analyzed was a game with ~750 classes with only takes a minute or two on an i3 processor with 6gb ram. This used to be a big concern as analyzing it used to take approximately 10 minutes. 

Do you know how many classes are in the binary you're working with?

**Comment by TheAifam5** [comment] 2020-04-08 17:39
I always run the plugin with following options:
- Find Fundamental types
- Fill class Fields
- Locate Constructors

`Locate Constructors` is what takes so much time mostly and crashes on big binaries.

I don't know how many classes are in the binary, but searching for "^(\*|_)?(Z([A-Z]|\d)|N\d)" shows: 1637 items.

**Comment by astrelsky** [comment] 2020-04-13 21:43
I have a database implementation partially functional at the moment. I only started it yesterday so its not ready to be pushed anytime soon but it is coming.

**Comment by astrelsky** [comment] 2020-04-19 02:38
I'm not pushing this commit because they are intrusive and some things are broken but progress is being made. I have to iron out some spaghetti code, deprecate some things and then document and stress test the rest. Unfortunately I have some exams next week and a report due so this probably won't make it into until early May.

```
[master f26b564] DB checkpoint 1
 28 files changed, 2237 insertions(+), 199 deletions(-)
 create mode 100644 src/main/java/ghidra/app/plugin/prototype/CppCodeAnalyzerPlugin/wrappers/WindowsClassTypeInfo.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/ClassTypeInfoManager.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/ClassTypeInfoManagerDB.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/DataBaseIterable.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/RecordIterable.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/typeinfo/AbstractClassTypeInfoDB.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/typeinfo/GnuClassTypeInfoDB.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/typeinfo/WindowsClassTypeInfoDB.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/vtable/AbstractVtableDB.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/vtable/VftableDB.java
 create mode 100644 src/main/java/ghidra/program/database/data/rtti/vtable/VtableModelDB.java
```

**Comment by astrelsky** [comment] 2020-06-18 00:34
@TheAifam5 if you're able to do would you mind giving the experimental branch a shot? I haven't backported it yet so it'll require the current ghidra dev branch.

**Comment by TheAifam5** [comment] 2020-06-18 15:51
@astrelsky Checking right now :)

**Comment by astrelsky** [comment] 2020-06-19 01:10
Wow, GitHub almost got me again with changing quote to edit message. Anyway...

> 
> There is alot of `Variable Utils returned wrong class structure!` printed logs.
> 

Unfortunately there always was. However I think I made an error reworking the logic there. https://github.com/NationalSecurityAgency/ghidra/issues/1210#issue-517202664

Looking into the stack trace. I'm assuming it threw up dialog boxes everywhere. I need to figure out a way to make it halt so that doesn't occur.

**Comment by TheAifam5** [comment] 2020-06-19 02:10
It froze Ghidra completely for a while but I gave it a time. After that 2 errors popped out, then I cancelled analysis.

**Comment by astrelsky** [comment] 2020-06-19 02:52
> It froze Ghidra completely for a while but I gave it a time. After that 2 errors popped out, then I cancelled analysis.

May you try letting it run until completion? Just the rtti analyzer and not the class analyzer. Knowing if it is just a handful of cases as opposed to 100s can help narrow it down. I'll come up with a non disruptive way of handling the error in the morning. This was at least the tree and what went through will be usable until the cause is tracked down.

**Comment by astrelsky** [comment] 2020-06-20 19:45
@TheAifam5 I believe I've fixed the freezing issue and the errors. If you could give it another shot it would be appreciated.

If you get an error when opening the program in ghidra it is because I changed one of the database schemas. To fix this open the code browser with no programs open, disable the plugin, open the program, run the `ResetDatabaseScript` script in the developer_scripts folder, save and close the program and then you can re-enable the plugin and re-open the program. 

There is no automatic upgrader at this time as I don't want to change the schema version numbers until it is moved out of the experimental branch.

**Comment by astrelsky** [comment] 2020-07-28 20:08
This should be fixed in the experimental branch. If you still have an issue using said branch please feel free to reopen this.

**Closed by astrelsky** 2020-07-28 20:08 UTC
Labels: in progress
