### ISSUE TITLE
Create vtable structs with function pointers

### ISSUE THREAD

**Issue by jrmuizel** [astrelsky/Ghidra-Cpp-Class-Analyzer#27] opened 2020-12-21 19:19 UTC
Currently it's very tedious to create the structs representing the vtable in Ghidra. It would be convenient if this extension could create those structs and function pointer types based off of the signatures of the destinations.

**Comment by astrelsky** [comment] 2020-12-22 01:07
> Currently it's very tedious to create the structs representing the vtable in Ghidra. It would be convenient if this extension could create those structs and function pointer types based off of the signatures of the destinations.

It does. You can get to it quickly by right-clicking on the type in the "ClassTypeInfo Tree" and selecting "Edit Data Type". From there just right click on the _vptr component and choose "Edit Component".

This should occur when the corresponding c++ class analyzer is run.

**Comment by jrmuizel** [comment] 2020-12-22 02:22
Hmmm... I seem to not have those things. I have "Edit" but the structure that I get is empty. Is there an example binary that is known to work well with this extension that I can compare with?

**Comment by astrelsky** [comment] 2020-12-22 02:33
> Hmmm... I seem to not have those things. I have "Edit" but the structure that I get is empty. Is there an example binary that is known to work well with this extension that I can compare with?

It is "Edit". I was going off memory. 

If the Structure is empty then the cause would be one of 3 things:

* No vtable
* Vtable wasn't found 
* Some other bug

If you are certain that there is s vtable for the class in question then this would definitely require further investigation.

**Comment by astrelsky** [comment] 2020-12-23 03:36
As a sanity check you can always run it on libstdc++.so and then check the iostream classes.

**Comment by jrmuizel** [comment] 2020-12-23 15:38
Ok, I think I have the analyzers running properly on this test case:
```
struct Bar {
        virtual int a(int x) = 0;
        virtual int b(double x, double y) = 0;
        virtual int get() = 0;
};

struct Foo : public Bar {
        int a(int ax) override {
                x = ax;
                return x;
        }
        int b(double ax, double ay) override {
                x = ax;
                y = ay;
                return y;
        }
        virtual int get() {
                return y;
        }
        int x;
        int y;
};

int main() {
        Bar* b = new Foo;
        b->a(4);
        b->b(6, 7);
        return b->get();
}
```
`Foo` and `Bar` both show up in the ClassTypeInfo Tree and both have "Goto Vtable". However the vtable* _vptr member of Bar is empty. I'd like it to be automatically/or semi-automatically filled in with 3 function pointers that have types matching the signatures of `a`, `b` and `get` respectively.

**Comment by astrelsky** [comment] 2020-12-24 02:22
This seems like a bug. I will investigate with the provided example tomorrow. The vtable structs shouldn't be empty.

**Comment by jrmuizel** [comment] 2020-12-24 03:13
FWIW, I built it with `gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)`

**Comment by astrelsky** [comment] 2020-12-25 01:49
I was able to reproduce this. I should have it fixed within a couple days.

**Comment by astrelsky** [comment] 2020-12-28 14:49
b6f24a7427f671518afa3e8ebe5f361b23531640 should have fixed the issue

**Closed** 2020-12-28 14:48 UTC

**Comment by jrmuizel** [comment] 2020-12-28 16:40
Yep. It works for me now.
